<?php
declare(strict_types=1);

require_once __DIR__.'/bank_certificate_manager.php';
require_once __DIR__.'/bank_http_client.php';
require_once __DIR__.'/bank_idempotency.php';
require_once __DIR__.'/oauth_token_manager.php';

/** Itaú Recebimentos: PIX v2 e Cobrança/Bolecode, sem APIs de saída. */
final class CobxItauConnector implements CobxPaymentConnector,CobxConnectorCapabilities,CobxConnectionTestable,CobxContextualPaymentConnector,CobxContextualConnectionTestable
{
    private const TOKEN_PROD='https://sts.itau.com.br/api/oauth/token';
    private const PIX_PROD='https://secure.api.itau/pix_recebimentos/v2';
    private const PIX_SANDBOX='https://devportal.itau.com.br/sandboxapi/pix_recebimentos_ext_v2/v2';
    private const BILLING_SANDBOX='https://devportal.itau.com.br/sandboxapi/cash_management_ext_v2/v2';

    public function provider():string{return'itau';}
    public function paymentMethods():array{return['pix','boleto'];}
    public function capabilities():array{return['pix_immediate','pix_due','pix_received','boleto','bolecode','webhook','cancel','fetch','reconciliation','sandbox_simplified','mtls_production','dynamic_certificate'];}
    public function testConnection(array $account):array{return['ok'=>false,'supported'=>true,'detail'=>'O teste Itaú exige contexto persistente; produção também exige certificado dinâmico.'];}
    public function fetch(array $account,string $externalId):array{return['ok'=>false,'detail'=>'A consulta Itaú exige contexto persistente.'];}
    public function cancel(array $account,string $externalId):array{return['ok'=>false,'detail'=>'O cancelamento Itaú exige contexto persistente.'];}

    public function testConnectionWithContext(PDO $pdo,array $a):array{try{if(($a['environment']??'sandbox')==='sandbox')return['ok'=>$this->sandboxToken($a)!=='','supported'=>true,'detail'=>'Credencial simplificada do sandbox Itaú disponível; não representa autenticação produtiva.'];return$this->withMtls($pdo,$a,function(array $m)use($pdo,$a):array{$meta=(new CobxBankCertificateManager())->metadata($pdo,(string)$a['id']);$token=$this->productionToken($pdo,$a,$m);return['ok'=>$token!=='','supported'=>true,'detail'=>'OAuth2/mTLS produtivo disponível. Certificado válido até '.(string)($meta['valid_until']??'data não identificada').'.'];});}catch(Throwable $e){return['ok'=>false,'supported'=>true,'detail'=>'Itaú: '.$e->getMessage()];}}
    public function create(PDO $pdo,array $a,array $charge,array $i,string $method):array{return$method==='boleto'?$this->createBoleto($pdo,$a,$charge,$i):$this->createPix($pdo,$a,$charge,$i);}

    private function createPix(PDO $pdo,array $a,array $charge,array $i):array{$c=(array)$a['provider_config'];$key=trim((string)($c['pix_key']??''));if($key==='')return['ok'=>false,'detail'=>'Itaú: configure a chave PIX.'];$doc=preg_replace('/\D+/','',(string)($charge['client_document']??''))?:'';if(!in_array(strlen($doc),[11,14],true))return['ok'=>false,'detail'=>'Itaú: pagador sem CPF/CNPJ válido.'];$txid=cobx_bank_txid((string)$i['id']);$kind=(string)$i['due_date']>date('Y-m-d')?'cobv':'cob';$payload=['calendario'=>$kind==='cobv'?['dataDeVencimento'=>(string)$i['due_date'],'validadeAposVencimento'=>30]:['expiracao'=>86400],'devedor'=>[strlen($doc)===11?'cpf':'cnpj'=>$doc,'nome'=>(string)$charge['client_name']],'valor'=>['original'=>number_format((float)$i['amount'],2,'.','')],'chave'=>$key,'solicitacaoPagador'=>mb_substr((string)$charge['description'],0,140)];try{$r=$this->request($pdo,$a,'pix','PUT','/'.$kind.'/'.rawurlencode($txid),$payload,cobx_bank_idempotency_key('itau',(string)$i['id'],'pix-'.$kind));if(!$r->ok())return$this->failure('criar PIX',$r);$j=$r->json()??[];$qr=$this->request($pdo,$a,'pix','GET','/'.$kind.'/'.rawurlencode($txid).'/qrcode');$qj=$qr->ok()?($qr->json()??[]):[];return['ok'=>true,'detail'=>'Itaú: PIX '.($kind==='cobv'?'com vencimento':'imediato').' criado.','external_id'=>$txid,'provider_reference'=>'itau:'.$kind.':'.cobx_bank_installment_reference((string)$i['id']),'txid'=>$txid,'payment_url'=>(string)($j['location']??''),'pix_copy_paste'=>(string)($j['pixCopiaECola']??$qj['pixCopiaECola']??''),'pix_qrcode'=>(string)($qj['imagemQrcode']??'')];}catch(Throwable $e){return['ok'=>false,'detail'=>'Itaú: '.$e->getMessage()];}}

    private function createBoleto(PDO $pdo,array $a,array $charge,array $i):array{$c=(array)$a['provider_config'];foreach(['agency','account','account_digit','wallet']as$k)if(trim((string)($c[$k]??''))==='')return['ok'=>false,'detail'=>'Itaú: configuração ausente: '.$k.'.'];$doc=preg_replace('/\D+/','',(string)($charge['client_document']??''))?:'';$our=substr(str_pad(preg_replace('/\D/','',(string)$i['id'])?:sprintf('%08u',crc32((string)$i['id'])),8,'0',STR_PAD_LEFT),-8);$payload=['etapa_processo_boleto'=>($a['environment']??'sandbox')==='production'?'efetivacao':'validacao','codigo_canal_operacao'=>'API','beneficiario'=>['id_beneficiario'=>(string)($c['beneficiary_id']??''),'agencia'=>(string)$c['agency'],'conta_corrente'=>(string)$c['account'],'digito_verificador_conta'=>(string)$c['account_digit']],'dado_boleto'=>['descricao_instrumento_cobranca'=>'boleto','tipo_boleto'=>'a vista','codigo_carteira'=>(string)$c['wallet'],'valor_total_titulo'=>number_format((float)$i['amount'],2,'.',''),'codigo_especie'=>'DS','data_emissao'=>date('Y-m-d'),'pagador'=>['pessoa'=>['nome_pessoa'=>(string)$charge['client_name'],'tipo_pessoa'=>['codigo_tipo_pessoa'=>strlen($doc)===11?'F':'J','numero_cadastro_pessoa_fisica'=>$doc]],'endereco'=>['nome_logradouro'=>(string)($charge['client_address_street']??''),'nome_bairro'=>(string)($charge['client_address_neighborhood']??''),'nome_cidade'=>(string)($charge['client_address_city']??''),'sigla_UF'=>strtoupper((string)($charge['client_address_state']??'')),'numero_CEP'=>preg_replace('/\D+/','',(string)($charge['client_address_postal_code']??''))]],'dados_individuais_boleto'=>[['numero_nosso_numero'=>$our,'data_vencimento'=>(string)$i['due_date'],'valor_titulo'=>number_format((float)$i['amount'],2,'.',''),'texto_seu_numero'=>substr((string)$i['id'],0,10)]]]];if((string)($c['bolecode_enabled']??'0')==='1')$payload['dado_boleto']['dados_qrcode']=['chave'=>$c['pix_key']??''];try{$r=$this->request($pdo,$a,'billing','POST','/boletos',$payload,cobx_bank_idempotency_key('itau',(string)$i['id'],'boleto'));if(!$r->ok())return$this->failure('emitir boleto/Bolecode',$r);$j=$r->json()??[];$d=$j['data']['dados_individuais_boleto'][0]??$j['dados_individuais_boleto'][0]??$j;return['ok'=>true,'detail'=>'Itaú: '.(!empty($d['pix_copia_e_cola'])?'Bolecode':'boleto').' emitido.','external_id'=>(string)($d['numero_nosso_numero']??$our),'provider_reference'=>'itau:boleto:'.cobx_bank_installment_reference((string)$i['id']),'txid'=>(string)($d['txid']??''),'payment_url'=>(string)($d['url_boleto']??''),'boleto_digitable_line'=>(string)($d['numero_linha_digitavel']??''),'boleto_pdf_url'=>(string)($d['url_boleto']??''),'pix_copy_paste'=>(string)($d['pix_copia_e_cola']??''),'pix_qrcode'=>''];}catch(Throwable $e){return['ok'=>false,'detail'=>'Itaú: '.$e->getMessage()];}}

    public function fetchWithContext(PDO $pdo,array $a,string $id):array{try{$kind=$this->resourceKind($pdo,$a,$id);if($kind==='boleto'){$c=(array)$a['provider_config'];$path='/boletos?'.http_build_query(['id_beneficiario'=>$c['beneficiary_id']??'','codigo_carteira'=>$c['wallet']??'','nosso_numero'=>$id]);$r=$this->request($pdo,$a,'billing','GET',$path);}else$r=$this->request($pdo,$a,'pix','GET','/'.$kind.'/'.rawurlencode($id));if(!$r->ok())return$this->failure('consultar recebimento',$r);$remote=$r->json()??[];$remote['_cobx_resource']=$kind;return['ok'=>true,'remote'=>$remote,'normalized'=>$this->normalize($remote)];}catch(Throwable $e){return['ok'=>false,'detail'=>'Itaú: '.$e->getMessage()];}}
    public function cancelWithContext(PDO $pdo,array $a,string $id):array{try{$kind=$this->resourceKind($pdo,$a,$id);if($kind==='boleto')$r=$this->request($pdo,$a,'billing','PATCH','/boletos/'.$id,['operacao'=>'BAIXA'],cobx_bank_idempotency_key('itau',$id,'baixa'));else$r=$this->request($pdo,$a,'pix','PATCH','/'.$kind.'/'.rawurlencode($id),['status'=>'REMOVIDA_PELO_USUARIO_RECEBEDOR'],cobx_bank_idempotency_key('itau',$id,'cancel-'.$kind));return$r->ok()?['ok'=>true,'detail'=>'Itaú: cancelamento/baixa solicitado.']:$this->failure('cancelar/baixar',$r);}catch(Throwable $e){return['ok'=>false,'detail'=>'Itaú: '.$e->getMessage()];}}

    public function normalize(array $remote):array{$kind=(string)($remote['_cobx_resource']??'cob');$r=$remote['data']['dados_individuais_boleto'][0]??$remote['dados_individuais_boleto'][0]??$remote;$original=(string)($r['status']??$r['situacao_geral_boleto']??$r['codigo_situacao_cobranca']??'');$u=mb_strtoupper($original);$status=match($u){'CONCLUIDA','PAGO','PAGA','LIQUIDADO','LIQUIDADA'=>'paid','ESTORNADO','ESTORNADA','BAIXADO','BAIXADA','CANCELADO','CANCELADA','REMOVIDA_PELO_USUARIO_RECEBEDOR'=>'cancelled','VENCIDO','VENCIDA'=>'overdue',default=>'pending'};$origin=mb_strtoupper((string)($r['origem_pagamento']??$r['tipo_pagamento']??''));if(str_contains($origin,'PIX'))$origin='PIX';elseif($kind==='boleto')$origin='BOLETO';else$origin='PIX';return['external_id'=>(string)($r['numero_nosso_numero']??$r['txid']??''),'status'=>$status,'provider_status'=>$original,'provider_event'=>$r['tipo_evento']??null,'payment_origin'=>$origin,'txid'=>$r['txid']??null,'provider_reference'=>$r['texto_seu_numero']??null,'paid_at'=>$r['horario']??$r['data_pagamento']??null,'receipt_url'=>$r['url_comprovante']??null,'boleto_digitable_line'=>$r['numero_linha_digitavel']??null,'boleto_pdf_url'=>$r['url_boleto']??null,'pix_copy_paste'=>$r['pix_copia_e_cola']??$r['pixCopiaECola']??null,'resource_kind'=>$kind];}
    public function verifyWebhook(PDO $pdo,string $companyId,string $raw,array $server,array $query):bool{if(($server['SSL_CLIENT_VERIFY']??'')!=='SUCCESS'&&trim((string)($server['HTTP_AUTHORIZATION']??''))==='')return false;$body=json_decode($raw,true);if(!is_array($body))return false;$q=$pdo->prepare("SELECT 1 FROM payment_accounts WHERE company_id=? AND provider='itau' AND is_active=1 LIMIT 1");$q->execute([$companyId]);return(bool)$q->fetchColumn();}
    public function webhookEvents(PDO $pdo,string $companyId,string $raw,array $query):array{$body=json_decode($raw,true);if(!is_array($body))return[];$items=isset($body['pix'])&&is_array($body['pix'])?$body['pix']:(array_is_list($body)?$body:[$body]);$out=[];foreach($items as$item){if(!is_array($item))continue;$id=(string)($item['numero_nosso_numero']??$item['txid']??'');if($id==='')continue;$q=$pdo->prepare("SELECT * FROM payment_accounts WHERE company_id=? AND provider='itau' AND is_active=1");$q->execute([$companyId]);foreach($q->fetchAll(PDO::FETCH_ASSOC)as$row){$f=$this->fetchWithContext($pdo,cobx_bank_account_hydrate($row),$id);if(empty($f['ok']))continue;$n=$f['normalized'];$out[]=['external_id'=>$id,'reference'=>(string)($n['provider_reference']??''),'amount'=>(float)($item['valor']??$item['valor_pagamento']??0),'paid_at'=>(string)($n['paid_at']??''),'status'=>(string)$n['status'],'provider_status'=>$n['provider_status']??null,'provider_event'=>$n['provider_event']??null,'payment_origin'=>$n['payment_origin']??null,'txid'=>$n['txid']??null];break;}}return$out;}

    private function request(PDO $pdo,array $a,string $product,string $method,string $path,?array $json=null,?string $key=null):CobxBankHttpResponse{$sandbox=($a['environment']??'sandbox')==='sandbox';$base=$product==='pix'?($sandbox?self::PIX_SANDBOX:self::PIX_PROD):$this->billingBase($a);$o=['retry_attempts'=>2];if($sandbox){$o['bearer']=$this->sandboxToken($a);$api=trim((string)($a['credentials']['sandbox_api_key']??''));if($api!=='')$o['headers']=['x-itau-apikey'=>$api];return$this->finishRequest($method,$base.$path,$o,$json,$key);}return$this->withMtls($pdo,$a,function(array $m)use($pdo,$a,$method,$base,$path,$o,$json,$key):CobxBankHttpResponse{$o['bearer']=$this->productionToken($pdo,$a,$m);$o['mtls']=$m;return$this->finishRequest($method,$base.$path,$o,$json,$key);});}
    private function finishRequest(string $method,string $url,array $o,?array $json,?string $key):CobxBankHttpResponse{if($json!==null)$o['json']=$json;if($key)$o['idempotency_key']=$key;return(new CobxBankHttpClient())->request($method,$url,$o);}
    private function productionToken(PDO $pdo,array $a,array $mtls):string{return(new CobxOAuthTokenManager())->get($pdo,$a,['token_url'=>self::TOKEN_PROD,'grant_type'=>'client_credentials','client_auth'=>'body'],$mtls);}
    private function sandboxToken(array $a):string{$token=trim((string)($a['credentials']['sandbox_access_token']??''));if($token==='')throw new RuntimeException('Access Token simplificado do sandbox não configurado.');return$token;}
    private function billingBase(array $a):string{if(($a['environment']??'sandbox')==='sandbox')return self::BILLING_SANDBOX;$base=rtrim(trim((string)($a['provider_config']['production_billing_base_url']??'')),'/');if($base===''||!str_starts_with($base,'https://'))throw new RuntimeException('URL produtiva oficial da Cobrança/Bolecode não configurada.');return$base;}
    private function withMtls(PDO $pdo,array $a,callable $cb):mixed{$m=new CobxBankCertificateManager();$meta=$m->metadata($pdo,(string)$a['id']);if(!$meta)throw new RuntimeException('certificado dinâmico não configurado.');if(!empty($meta['valid_until'])&&new DateTimeImmutable((string)$meta['valid_until'])<=new DateTimeImmutable())throw new RuntimeException('certificado dinâmico expirado em '.$meta['valid_until'].'.');$material=$m->material($pdo,(string)$a['id']);if(!$material||empty($material['certificate_pem'])||empty($material['private_key_pem']))throw new RuntimeException('CRT/KEY do certificado dinâmico incompletos.');$files=$m->temporaryFiles($material);try{return$cb($files);}finally{$m->cleanup($files);}}
    private function resourceKind(PDO $pdo,array $a,string $id):string{$q=$pdo->prepare('SELECT provider_reference FROM installments i JOIN charges ch ON ch.id=i.charge_id WHERE ch.payment_account_id=? AND i.external_id=? LIMIT 1');$q->execute([$a['id'],$id]);$ref=(string)($q->fetchColumn()?:'');if(str_starts_with($ref,'itau:boleto:'))return'boleto';if(str_starts_with($ref,'itau:cobv:'))return'cobv';return'cob';}
    private function failure(string $op,CobxBankHttpResponse $r):array{$j=$r->json();$msg=is_array($j)?(string)($j['mensagem']??$j['message']??$j['detail']??''):'';return['ok'=>false,'detail'=>'Itaú: falha ao '.$op.' (HTTP '.$r->status.')'.($msg!==''?' - '.$msg:'').'.'];}
}
