<?php
declare(strict_types=1);

require_once __DIR__.'/bank_certificate_manager.php';
require_once __DIR__.'/bank_http_client.php';
require_once __DIR__.'/bank_idempotency.php';
require_once __DIR__.'/oauth_token_manager.php';

/** Santander Recebimentos: PIX QR Code e Hub de Cobrança v2 com Workspace. */
final class CobxSantanderConnector implements CobxPaymentConnector,CobxConnectorCapabilities,CobxConnectionTestable,CobxContextualPaymentConnector,CobxContextualConnectionTestable
{
    private const BILLING_PROD='https://trust-open.api.santander.com.br';
    private const BILLING_SANDBOX='https://trust-sandbox.api.santander.com.br';
    private const PIX_PROD='https://trust-pix.santander.com.br';
    private const PIX_SANDBOX='https://trust-pix-h.santander.com.br';

    public function provider():string{return'santander';}
    public function paymentMethods():array{return['pix','boleto'];}
    public function capabilities():array{return['pix_immediate','pix_due','pix_received','boleto','boleto_pix','workspace','webhook','cancel','fetch','pdf','reconciliation','sandbox','mtls'];}
    public function testConnection(array $account):array{return['ok'=>false,'supported'=>true,'detail'=>'O teste Santander exige contexto seguro e certificado mTLS.'];}
    public function fetch(array $account,string $externalId):array{return['ok'=>false,'detail'=>'A consulta Santander exige contexto persistente.'];}
    public function cancel(array $account,string $externalId):array{return['ok'=>false,'detail'=>'A instrução Santander exige contexto persistente.'];}

    public function testConnectionWithContext(PDO $pdo,array $a):array{try{return$this->withMtls($pdo,$a,function(array $m)use($pdo,$a):array{$token=$this->token($pdo,$a,'billing',$m);$workspace=$this->billingRequest($pdo,$a,'GET','/collection_bill_management/v2/workspaces/'.rawurlencode($this->requiredConfig($a,'workspace_id')),$m);return['ok'=>$token!==''&&$workspace->ok(),'supported'=>true,'detail'=>$workspace->ok()?'Credenciais, certificado e Workspace Santander válidos.':'Token válido; Workspace não confirmada (HTTP '.$workspace->status.').'];});}catch(Throwable $e){return['ok'=>false,'supported'=>true,'detail'=>'Santander: '.$e->getMessage()];}}
    public function create(PDO $pdo,array $a,array $charge,array $installment,string $method):array{return$method==='boleto'?$this->createBoleto($pdo,$a,$charge,$installment):$this->createPix($pdo,$a,$charge,$installment);}

    private function createPix(PDO $pdo,array $a,array $charge,array $i):array
    {
        $key=$this->requiredConfig($a,'pix_key');$doc=preg_replace('/\D+/','',(string)($charge['client_document']??''))?:'';if(!in_array(strlen($doc),[11,14],true))return['ok'=>false,'detail'=>'Santander: pagador sem CPF/CNPJ válido.'];$txid=cobx_bank_txid((string)$i['id']);$kind=(string)$i['due_date']>date('Y-m-d')?'cobv':'cob';$payload=['calendario'=>$kind==='cobv'?['dataDeVencimento'=>(string)$i['due_date'],'validadeAposVencimento'=>30]:['expiracao'=>86400],'devedor'=>[strlen($doc)===11?'cpf':'cnpj'=>$doc,'nome'=>(string)$charge['client_name']],'valor'=>['original'=>number_format((float)$i['amount'],2,'.','')],'chave'=>$key,'solicitacaoPagador'=>mb_substr((string)$charge['description'],0,140)];
        try{return$this->withMtls($pdo,$a,function(array $m)use($pdo,$a,$payload,$txid,$kind,$i):array{$r=$this->pixRequest($pdo,$a,'PUT','/api/v1/'.$kind.'/'.rawurlencode($txid),$m,$payload,cobx_bank_idempotency_key('santander',(string)$i['id'],'pix-'.$kind));if(!$r->ok())return$this->failure('criar PIX',$r);$j=$r->json()??[];return['ok'=>true,'detail'=>'Santander: PIX '.($kind==='cobv'?'com vencimento':'imediato').' criado.','external_id'=>$txid,'provider_reference'=>'santander:'.$kind.':'.cobx_bank_installment_reference((string)$i['id']),'txid'=>$txid,'payment_url'=>(string)($j['location']??''),'pix_copy_paste'=>(string)($j['pixCopiaECola']??''),'pix_qrcode'=>''];});}catch(Throwable $e){return['ok'=>false,'detail'=>'Santander: '.$e->getMessage()];}
    }

    private function createBoleto(PDO $pdo,array $a,array $charge,array $i):array
    {
        foreach(['workspace_id','covenant','beneficiary_code','document_kind']as$k)$this->requiredConfig($a,$k);$c=(array)$a['provider_config'];$doc=preg_replace('/\D+/','',(string)($charge['client_document']??''))?:'';if(!in_array(strlen($doc),[11,14],true))return['ok'=>false,'detail'=>'Santander: pagador sem CPF/CNPJ válido.'];$nsu=substr(hash('sha256',(string)$i['id']),0,20);$payload=['nsuCode'=>$nsu,'nsuDate'=>date('Y-m-d'),'environment'=>($a['environment']??'sandbox')==='production'?'PRODUCAO':'TESTE','covenantCode'=>(string)$c['covenant'],'clientNumber'=>substr($nsu,0,15),'dueDate'=>(string)$i['due_date'],'issueDate'=>date('Y-m-d'),'documentKind'=>(string)$c['document_kind'],'nominalValue'=>number_format((float)$i['amount'],2,'.',''),'paymentType'=>'REGISTRO','payer'=>['documentType'=>strlen($doc)===11?'CPF':'CNPJ','documentNumber'=>$doc,'name'=>mb_substr((string)$charge['client_name'],0,40),'address'=>mb_substr(trim((string)($charge['client_address_street']??'').' '.(string)($charge['client_address_number']??'')),0,40),'neighborhood'=>mb_substr((string)($charge['client_address_neighborhood']??''),0,30),'city'=>mb_substr((string)($charge['client_address_city']??''),0,20),'state'=>strtoupper((string)($charge['client_address_state']??'')),'zipCode'=>preg_replace('/\D+/','',(string)($charge['client_address_postal_code']??''))],'messages'=>[mb_substr((string)$charge['description'],0,100)]];if((string)($c['bolepix_enabled']??'0')==='1')$payload['key']=['type'=>$this->pixKeyType((string)$c['pix_key']),'dictKey'=>(string)$c['pix_key']];
        try{return$this->withMtls($pdo,$a,function(array $m)use($pdo,$a,$payload,$i):array{$workspace=$this->requiredConfig($a,'workspace_id');$r=$this->billingRequest($pdo,$a,'POST','/collection_bill_management/v2/workspaces/'.rawurlencode($workspace).'/bank_slips',$m,$payload,cobx_bank_idempotency_key('santander',(string)$i['id'],'boleto'));if(!$r->ok())return$this->failure('registrar boleto',$r);$j=$r->json()??[];$bank=(string)($j['bankNumber']??$j['bankSlipId']??'');if($bank==='')return['ok'=>false,'detail'=>'Santander: registro aceito sem Nosso Número/ID.'];return['ok'=>true,'detail'=>'Santander: '.(!empty($j['qrCodePix'])?'Boleto SX/BolePix':'boleto').' registrado.','external_id'=>$bank,'provider_reference'=>'santander:boleto:'.cobx_bank_installment_reference((string)$i['id']),'txid'=>(string)($j['txId']??''),'payment_url'=>(string)($j['qrCodeUrl']??''),'boleto_digitable_line'=>(string)($j['digitableLine']??''),'boleto_pdf_url'=>'','pix_copy_paste'=>(string)($j['qrCodePix']??''),'pix_qrcode'=>''];});}catch(Throwable $e){return['ok'=>false,'detail'=>'Santander: '.$e->getMessage()];}
    }

    public function fetchWithContext(PDO $pdo,array $a,string $id):array{try{return$this->withMtls($pdo,$a,function(array $m)use($pdo,$a,$id):array{$kind=$this->resourceKind($pdo,$a,$id);if($kind==='boleto'){$path='/collection_bill_management/v2/bills?'.http_build_query(['beneficiaryCode'=>$this->requiredConfig($a,'beneficiary_code'),'bankNumber'=>$id]);$r=$this->billingRequest($pdo,$a,'GET',$path,$m);}else$r=$this->pixRequest($pdo,$a,'GET','/api/v1/'.$kind.'/'.rawurlencode($id),$m);if(!$r->ok())return$this->failure('consultar recebimento',$r);$remote=$r->json()??[];$remote['_cobx_resource']=$kind;$n=$this->normalize($remote);return['ok'=>true,'remote'=>$remote,'normalized'=>$n];});}catch(Throwable $e){return['ok'=>false,'detail'=>'Santander: '.$e->getMessage()];}}
    public function cancelWithContext(PDO $pdo,array $a,string $id):array{try{return$this->withMtls($pdo,$a,function(array $m)use($pdo,$a,$id):array{$kind=$this->resourceKind($pdo,$a,$id);if($kind==='boleto'){$payload=['covenantCode'=>$this->requiredConfig($a,'covenant'),'bankNumber'=>$id,'operation'=>'BAIXAR'];$path='/collection_bill_management/v2/workspaces/'.rawurlencode($this->requiredConfig($a,'workspace_id')).'/bank_slips';$r=$this->billingRequest($pdo,$a,'PATCH',$path,$m,$payload,cobx_bank_idempotency_key('santander',$id,'baixar'));}else$r=$this->pixRequest($pdo,$a,'PATCH','/api/v1/'.$kind.'/'.rawurlencode($id),$m,['status'=>'REMOVIDA_PELO_USUARIO_RECEBEDOR'],cobx_bank_idempotency_key('santander',$id,'cancel-'.$kind));return$r->ok()?['ok'=>true,'detail'=>'Santander: instrução de baixa/cancelamento enviada.']:$this->failure('baixar/cancelar',$r);});}catch(Throwable $e){return['ok'=>false,'detail'=>'Santander: '.$e->getMessage()];}}

    public function normalize(array $remote):array{$kind=(string)($remote['_cobx_resource']??'cob');$r=is_array($remote[0]??null)?$remote[0]:$remote;$original=(string)($r['status']??$r['situation']??$r['function']??'');$u=mb_strtoupper($original);$status=match($u){'CONCLUIDA','CONCLUDED','PAGO','PAGAMENTO','LIQUIDADO'=>'paid','ESTORNO','ESTORNADO','REMOVIDA_PELO_USUARIO_RECEBEDOR','REMOVED_BY_RECEIVING_USER','BAIXADO','CANCELADO'=>'cancelled','VENCIDO'=>'overdue',default=>'pending'};$origin=mb_strtoupper((string)($r['paymentType']??''));if($origin==='PIX')$origin='PIX';elseif($kind==='boleto'||$origin!=='')$origin='BOLETO';return['external_id'=>(string)($r['bankNumber']??$r['bankSlipId']??$r['txid']??$r['txId']??''),'status'=>$status,'provider_status'=>$original,'provider_event'=>$r['function']??null,'payment_origin'=>$origin,'txid'=>$r['txid']??$r['txId']??null,'provider_reference'=>$r['participantCode']??$r['clientNumber']??null,'paid_at'=>$r['paymentDate']??$r['horario']??null,'receipt_url'=>null,'boleto_digitable_line'=>$r['digitableLine']??null,'boleto_pdf_url'=>null,'pix_copy_paste'=>$r['qrCodePix']??$r['pixCopiaECola']??null,'resource_kind'=>$kind];}
    public function verifyWebhook(PDO $pdo,string $companyId,string $raw,array $server,array $query):bool{$body=json_decode($raw,true);if(!is_array($body))return false;$known=isset($body['pix'])||isset($body['txid'])||isset($body['txId'])||in_array(mb_strtoupper((string)($body['function']??'')),['PAGAMENTO','ESTORNO'],true);if(!$known)return false;$q=$pdo->prepare("SELECT 1 FROM payment_accounts WHERE company_id=? AND provider='santander' AND is_active=1 LIMIT 1");$q->execute([$companyId]);return(bool)$q->fetchColumn();}
    public function webhookEvents(PDO $pdo,string $companyId,string $raw,array $query):array{$body=json_decode($raw,true);if(!is_array($body))return[];$items=isset($body['pix'])&&is_array($body['pix'])?$body['pix']:(array_is_list($body)?$body:[$body]);$out=[];foreach($items as$item){if(!is_array($item))continue;$id=(string)($item['bankNumber']??$item['txid']??$item['txId']??'');if($id==='')continue;$q=$pdo->prepare("SELECT * FROM payment_accounts WHERE company_id=? AND provider='santander' AND is_active=1");$q->execute([$companyId]);foreach($q->fetchAll(PDO::FETCH_ASSOC)as$row){$f=$this->fetchWithContext($pdo,cobx_bank_account_hydrate($row),$id);if(empty($f['ok']))continue;$n=$f['normalized'];$function=mb_strtoupper((string)($item['function']??''));$status=$function==='ESTORNO'?'cancelled':(string)$n['status'];$origin=mb_strtoupper((string)($item['paymentType']??''))==='PIX'?'PIX':'BOLETO';$out[]=['external_id'=>$id,'reference'=>(string)($n['provider_reference']??$item['clientNumber']??''),'amount'=>(float)($item['paidValue']??$item['paymentValue']??$item['valor']??0),'paid_at'=>(string)($item['paymentDate']??$n['paid_at']??''),'status'=>$status,'provider_status'=>$n['provider_status']??$function,'provider_event'=>$function,'payment_origin'=>$origin,'txid'=>$item['txId']??$item['txid']??null];break;}}return$out;}

    private function token(PDO $pdo,array $a,string $product,array $mtls):string{$copy=$a;$cr=(array)$a['credentials'];if($product==='pix'){$copy['credentials']['client_id']=$cr['pix_client_id']??$cr['client_id']??'';$copy['credentials']['client_secret']=$cr['pix_client_secret']??$cr['client_secret']??'';$base=($a['environment']??'sandbox')==='production'?self::PIX_PROD:self::PIX_SANDBOX;$url=$base.'/oauth/token';}else{$base=($a['environment']??'sandbox')==='production'?self::BILLING_PROD:self::BILLING_SANDBOX;$url=$base.'/auth/oauth/v2/token';}return(new CobxOAuthTokenManager())->get($pdo,$copy,['token_url'=>$url,'grant_type'=>'client_credentials','client_auth'=>'body'],$mtls);}
    private function pixRequest(PDO $pdo,array $a,string $method,string $path,array $mtls,?array $json=null,?string $key=null):CobxBankHttpResponse{$base=($a['environment']??'sandbox')==='production'?self::PIX_PROD:self::PIX_SANDBOX;$o=['bearer'=>$this->token($pdo,$a,'pix',$mtls),'mtls'=>$mtls,'retry_attempts'=>2];if($json!==null)$o['json']=$json;if($key)$o['idempotency_key']=$key;return(new CobxBankHttpClient())->request($method,$base.$path,$o);}
    private function billingRequest(PDO $pdo,array $a,string $method,string $path,array $mtls,?array $json=null,?string $key=null):CobxBankHttpResponse{$base=($a['environment']??'sandbox')==='production'?self::BILLING_PROD:self::BILLING_SANDBOX;$client=(string)($a['credentials']['client_id']??'');$o=['bearer'=>$this->token($pdo,$a,'billing',$mtls),'mtls'=>$mtls,'headers'=>['X-Application-Key'=>$client],'retry_attempts'=>2];if($json!==null)$o['json']=$json;if($key)$o['idempotency_key']=$key;return(new CobxBankHttpClient())->request($method,$base.$path,$o);}
    private function withMtls(PDO $pdo,array $a,callable $cb):mixed{$m=new CobxBankCertificateManager();$material=$m->material($pdo,(string)$a['id']);if(!$material||empty($material['certificate_pem'])||empty($material['private_key_pem']))throw new RuntimeException('certificado e chave mTLS não configurados.');$files=$m->temporaryFiles($material);try{return$cb($files);}finally{$m->cleanup($files);}}
    private function requiredConfig(array $a,string $key):string{$v=trim((string)($a['provider_config'][$key]??''));if($v==='')throw new RuntimeException('configuração obrigatória ausente: '.$key.'.');return$v;}
    private function resourceKind(PDO $pdo,array $a,string $id):string{$q=$pdo->prepare('SELECT provider_reference FROM installments i JOIN charges ch ON ch.id=i.charge_id WHERE ch.payment_account_id=? AND i.external_id=? LIMIT 1');$q->execute([$a['id'],$id]);$ref=(string)($q->fetchColumn()?:'');if(str_starts_with($ref,'santander:boleto:'))return'boleto';if(str_starts_with($ref,'santander:cobv:'))return'cobv';return'cob';}
    private function pixKeyType(string $key):string{if(filter_var($key,FILTER_VALIDATE_EMAIL))return'EMAIL';$digits=preg_replace('/\D+/','',$key)?:'';if(strlen($digits)===11)return'CPF';if(strlen($digits)===14)return'CNPJ';if(str_starts_with($key,'+'))return'CELULAR';return'EVP';}
    private function failure(string $op,CobxBankHttpResponse $r):array{$j=$r->json();$message=is_array($j)?(string)($j['message']??$j['detail']??$j['error_description']??''):'';return['ok'=>false,'detail'=>'Santander: falha ao '.$op.' (HTTP '.$r->status.')'.($message!==''?' - '.$message:'').'.'];}
}
