<?php
declare(strict_types=1);

require_once __DIR__.'/bank_certificate_manager.php';
require_once __DIR__.'/bank_http_client.php';
require_once __DIR__.'/bank_idempotency.php';
require_once __DIR__.'/oauth_token_manager.php';

/** Provider Sicoob restrito a recebimentos: PIX e Cobrança Bancária v3. */
final class CobxSicoobConnector implements CobxPaymentConnector,CobxConnectorCapabilities,CobxConnectionTestable,CobxContextualPaymentConnector,CobxContextualConnectionTestable
{
    private const TOKEN_URL='https://auth.sicoob.com.br/auth/realms/cooperado/protocol/openid-connect/token';
    private const PIX_PROD='https://api.sicoob.com.br/pix/api/v2';
    private const PIX_SANDBOX='https://sandbox.sicoob.com.br/sicoob/sandbox/pix/api/v2';
    private const BILLING_PROD='https://api.sicoob.com.br/cobranca-bancaria/v3';
    private const BILLING_SANDBOX='https://sandbox.sicoob.com.br/sicoob/sandbox/cobranca-bancaria/v3';

    public function provider():string{return'sicoob';}
    public function paymentMethods():array{return['pix','boleto'];}
    public function capabilities():array{return['pix_immediate','pix_due','boleto','boleto_pix_optional','webhook','cancel','fetch','pdf','reconciliation','sandbox','mtls'];}
    public function testConnection(array $account):array{return['ok'=>false,'supported'=>true,'detail'=>'O teste Sicoob requer contexto seguro e certificado mTLS.'];}
    public function fetch(array $account,string $externalId):array{return['ok'=>false,'detail'=>'A consulta Sicoob requer contexto persistente.'];}
    public function cancel(array $account,string $externalId):array{return['ok'=>false,'detail'=>'A baixa Sicoob requer contexto persistente.'];}

    public function testConnectionWithContext(PDO $pdo,array $account):array
    {
        try{return $this->withMtls($pdo,$account,function(array $mtls)use($pdo,$account):array{$token=$this->accessToken($pdo,$account,'pix',$mtls);return $token!==''?['ok'=>true,'supported'=>true,'detail'=>'Credencial Sicoob e certificado mTLS disponíveis para PIX Recebimentos.']:['ok'=>false,'supported'=>true,'detail'=>'Token Sicoob indisponível.'];});}
        catch(Throwable $e){return['ok'=>false,'supported'=>true,'detail'=>'Sicoob: '.$e->getMessage()];}
    }

    public function create(PDO $pdo,array $account,array $charge,array $installment,string $method):array
    {
        return $method==='boleto'?$this->createBoleto($pdo,$account,$charge,$installment):$this->createPix($pdo,$account,$charge,$installment);
    }

    private function createPix(PDO $pdo,array $account,array $charge,array $installment):array
    {
        $config=(array)($account['provider_config']??[]);$key=trim((string)($config['pix_key']??''));if($key==='')return['ok'=>false,'detail'=>'Sicoob: configure a chave PIX recebedora.'];
        $doc=preg_replace('/\D+/','',(string)($charge['client_document']??''))?:'';if(!in_array(strlen($doc),[11,14],true))return['ok'=>false,'detail'=>'Sicoob: pagador sem CPF/CNPJ válido.'];
        $txid=cobx_bank_txid((string)$installment['id']);$kind=(string)$installment['due_date']>date('Y-m-d')?'cobv':'cob';
        $payload=['calendario'=>$kind==='cobv'?['dataDeVencimento'=>(string)$installment['due_date'],'validadeAposVencimento'=>30]:['expiracao'=>86400],'devedor'=>[strlen($doc)===11?'cpf':'cnpj'=>$doc,'nome'=>(string)$charge['client_name']],'valor'=>['original'=>number_format((float)$installment['amount'],2,'.','')],'chave'=>$key,'solicitacaoPagador'=>mb_substr((string)$charge['description'],0,140),'infoAdicionais'=>[['nome'=>'referencia','valor'=>cobx_bank_installment_reference((string)$installment['id'])]]];
        try{return $this->withMtls($pdo,$account,function(array $mtls)use($pdo,$account,$payload,$txid,$kind,$installment):array{$response=$this->request($pdo,$account,'pix','PUT','/'.$kind.'/'.rawurlencode($txid),$mtls,$payload,cobx_bank_idempotency_key('sicoob',(string)$installment['id'],'pix-'.$kind));if(!$response->ok())return$this->failure('criar PIX',$response);$remote=$response->json()??[];$image=$this->request($pdo,$account,'pix','GET','/'.$kind.'/'.rawurlencode($txid).'/imagem',$mtls);return['ok'=>true,'detail'=>'Sicoob: PIX '.($kind==='cobv'?'com vencimento':'imediato').' criado.','external_id'=>$txid,'provider_reference'=>'sicoob:'.$kind.':'.cobx_bank_installment_reference((string)$installment['id']),'txid'=>$txid,'payment_url'=>(string)($remote['location']??''),'pix_copy_paste'=>(string)($remote['pixCopiaECola']??''),'pix_qrcode'=>$image->ok()?base64_encode($image->body):''];});}catch(Throwable $e){return['ok'=>false,'detail'=>'Sicoob: '.$e->getMessage()];}
    }

    private function createBoleto(PDO $pdo,array $account,array $charge,array $installment):array
    {
        $c=(array)($account['provider_config']??[]);foreach(['numero_cliente','codigo_modalidade','numero_conta_corrente','codigo_especie_documento','identificacao_emissao_boleto','identificacao_distribuicao_boleto']as$key)if(trim((string)($c[$key]??''))==='')return['ok'=>false,'detail'=>'Sicoob: configuração obrigatória ausente: '.$key.'.'];
        $doc=preg_replace('/\D+/','',(string)($charge['client_document']??''))?:'';if(!in_array(strlen($doc),[11,14],true))return['ok'=>false,'detail'=>'Sicoob: pagador sem CPF/CNPJ válido.'];
        foreach(['client_address_street','client_address_neighborhood','client_address_city','client_address_state','client_address_postal_code']as$field)if(trim((string)($charge[$field]??''))==='')return['ok'=>false,'detail'=>'Sicoob: complete o endereço do pagador para emitir boleto.'];
        $payload=['numeroCliente'=>(int)$c['numero_cliente'],'codigoModalidade'=>(int)$c['codigo_modalidade'],'numeroContaCorrente'=>(int)$c['numero_conta_corrente'],'codigoEspecieDocumento'=>(string)$c['codigo_especie_documento'],'dataEmissao'=>date('Y-m-d'),'seuNumero'=>'C'.substr(hash('sha256',(string)$installment['id']),0,17),'identificacaoBoletoEmpresa'=>cobx_bank_installment_reference((string)$installment['id']),'identificacaoEmissaoBoleto'=>(int)$c['identificacao_emissao_boleto'],'identificacaoDistribuicaoBoleto'=>(int)$c['identificacao_distribuicao_boleto'],'valor'=>round((float)$installment['amount'],2),'dataVencimento'=>(string)$installment['due_date'],'numeroParcela'=>(int)$installment['installment_number'],'aceite'=>false,'pagador'=>['numeroCpfCnpj'=>$doc,'nome'=>(string)$charge['client_name'],'endereco'=>trim((string)$charge['client_address_street'].' '.(string)($charge['client_address_number']??'')),'bairro'=>(string)$charge['client_address_neighborhood'],'cidade'=>(string)$charge['client_address_city'],'cep'=>preg_replace('/\D+/','',(string)$charge['client_address_postal_code']),'uf'=>strtoupper((string)$charge['client_address_state']),'email'=>(string)($charge['client_email']??'')],'mensagensInstrucao'=>[mb_substr((string)$charge['description'],0,80)],'gerarPdf'=>true];
        if(trim((string)($c['numero_contrato_cobranca']??''))!=='')$payload['numeroContratoCobranca']=(int)$c['numero_contrato_cobranca'];if((string)($c['boleto_hibrido']??'0')==='1')$payload['codigoCadastrarPIX']=1;
        try{return $this->withMtls($pdo,$account,function(array $mtls)use($pdo,$account,$payload,$installment):array{$response=$this->request($pdo,$account,'billing','POST','/boletos',$mtls,$payload,cobx_bank_idempotency_key('sicoob',(string)$installment['id'],'boleto'));if(!$response->ok())return$this->failure('emitir boleto',$response);$json=$response->json()??[];$r=is_array($json['resultado']??null)?$json['resultado']:$json;$our=trim((string)($r['nossoNumero']??''));if($our==='')return['ok'=>false,'detail'=>'Sicoob: emissão aceita sem nosso número.'];$pdf=(string)($r['pdfBoleto']??'');return['ok'=>true,'detail'=>'Sicoob: boleto'.(!empty($r['qrCode'])?' híbrido':'').' emitido.','external_id'=>$our,'provider_reference'=>'sicoob:boleto:'.cobx_bank_installment_reference((string)$installment['id']),'txid'=>(string)($r['txid']??''),'payment_url'=>'','boleto_digitable_line'=>(string)($r['linhaDigitavel']??''),'boleto_pdf_url'=>$pdf!==''?'data:application/pdf;base64,'.$pdf:'','pix_copy_paste'=>(string)($r['qrCode']??''),'pix_qrcode'=>''];});}catch(Throwable $e){return['ok'=>false,'detail'=>'Sicoob: '.$e->getMessage()];}
    }

    public function fetchWithContext(PDO $pdo,array $account,string $externalId):array
    {
        try{return $this->withMtls($pdo,$account,function(array $mtls)use($pdo,$account,$externalId):array{$kind=$this->resourceKind($pdo,$account,$externalId);if($kind==='boleto'){$path='/boletos?'.http_build_query($this->billingQuery($account)+['nossoNumero'=>$externalId]);$response=$this->request($pdo,$account,'billing','GET',$path,$mtls);}else$response=$this->request($pdo,$account,'pix','GET','/'.$kind.'/'.rawurlencode($externalId),$mtls);if(!$response->ok())return$this->failure('consultar recebimento',$response);$remote=$response->json()??[];$remote['_cobx_resource']=$kind;$n=$this->normalize($remote);if($kind==='boleto'){$r=is_array($remote['resultado']??null)?$remote['resultado']:$remote;$second=$this->request($pdo,$account,'billing','GET','/boletos/segunda-via?'.http_build_query($this->billingQuery($account)+['nossoNumero'=>$externalId]),$mtls);$sj=$second->ok()?($second->json()??[]):[];$sr=is_array($sj['resultado']??null)?$sj['resultado']:$sj;$pdf=(string)($sr['pdfBoleto']??$r['pdfBoleto']??'');$n['boleto_digitable_line']=$r['linhaDigitavel']??null;$n['boleto_pdf_url']=$pdf!==''?'data:application/pdf;base64,'.$pdf:null;$n['pix_copy_paste']=$r['qrCode']??null;}return['ok'=>true,'remote'=>$remote,'normalized'=>$n];});}catch(Throwable $e){return['ok'=>false,'detail'=>'Sicoob: '.$e->getMessage()];}
    }

    public function cancelWithContext(PDO $pdo,array $account,string $externalId):array
    {
        try{return $this->withMtls($pdo,$account,function(array $mtls)use($pdo,$account,$externalId):array{$kind=$this->resourceKind($pdo,$account,$externalId);if($kind==='boleto'){$payload=$this->billingQuery($account);$response=$this->request($pdo,$account,'billing','POST','/boletos/'.rawurlencode($externalId).'/baixar',$mtls,$payload,cobx_bank_idempotency_key('sicoob',$externalId,'baixar'));}else$response=$this->request($pdo,$account,'pix','PATCH','/'.$kind.'/'.rawurlencode($externalId),$mtls,['status'=>'REMOVIDA_PELO_USUARIO_RECEBEDOR'],cobx_bank_idempotency_key('sicoob',$externalId,'cancel-'.$kind));return$response->ok()?['ok'=>true,'detail'=>'Sicoob: recebimento baixado/cancelado.']:$this->failure('baixar/cancelar recebimento',$response);});}catch(Throwable $e){return['ok'=>false,'detail'=>'Sicoob: '.$e->getMessage()];}
    }

    public function normalize(array $remote):array{$kind=(string)($remote['_cobx_resource']??'cob');$r=is_array($remote['resultado']??null)?$remote['resultado']:$remote;$original=trim((string)($r['situacaoBoleto']??$r['status']??''));$upper=mb_strtoupper($original);$status=match($upper){'CONCLUIDA','LIQUIDADO','LIQUIDADA','PAGO','PAGA'=>'paid','BAIXADO','BAIXADA','CANCELADO','CANCELADA','REMOVIDA_PELO_USUARIO_RECEBEDOR','REMOVIDA_PELO_PSP'=>'cancelled','VENCIDO','VENCIDA','EM ATRASO'=>'overdue',default=>'pending'};return['external_id'=>(string)($r['nossoNumero']??$r['txid']??''),'status'=>$status,'provider_status'=>$original,'provider_event'=>null,'payment_origin'=>!empty($r['qrCode'])?'PIX_OU_BOLETO':($kind==='boleto'?'BOLETO':'PIX'),'txid'=>$r['txid']??null,'provider_reference'=>$r['identificacaoBoletoEmpresa']??$r['seuNumero']??null,'paid_at'=>$r['horario']??$r['dataPagamento']??null,'receipt_url'=>null,'resource_kind'=>$kind];}
    public function verifyWebhook(PDO $pdo,string $companyId,string $raw,array $server,array $query):bool{if(strtoupper((string)($server['SSL_CLIENT_VERIFY']??''))!=='SUCCESS')return false;$q=$pdo->prepare("SELECT 1 FROM payment_accounts WHERE company_id=? AND provider='sicoob' AND is_active=1 LIMIT 1");$q->execute([$companyId]);return(bool)$q->fetchColumn();}
    public function webhookEvents(PDO $pdo,string $companyId,string $raw,array $query):array{$body=json_decode($raw,true);if(!is_array($body))return[];$items=isset($body['pix'])&&is_array($body['pix'])?$body['pix']:(array_is_list($body)?$body:[$body]);$out=[];foreach($items as$item){if(!is_array($item))continue;$original=(string)($item['situacaoBoleto']??$item['status']??'CONCLUIDA');$upper=mb_strtoupper($original);$paid=in_array($upper,['CONCLUIDA','LIQUIDADO','LIQUIDADA','PAGO','PAGA'],true);$out[]=['external_id'=>(string)($item['nossoNumero']??$item['txid']??''),'reference'=>(string)($item['identificacaoBoletoEmpresa']??$item['seuNumero']??''),'amount'=>(float)($item['valorPago']??$item['valor']??0),'paid_at'=>(string)($item['horario']??$item['dataPagamento']??''),'status'=>$paid?'paid':'pending','provider_status'=>$original,'payment_origin'=>$item['origemRecebimento']??(isset($item['txid'])?'PIX':'BOLETO'),'txid'=>$item['txid']??null];}return$out;}

    private function billingQuery(array $a):array{$c=(array)($a['provider_config']??[]);$q=['numeroCliente'=>(int)($c['numero_cliente']??0),'codigoModalidade'=>(int)($c['codigo_modalidade']??0)];if(trim((string)($c['numero_contrato_cobranca']??''))!=='')$q['numeroContratoCobranca']=(int)$c['numero_contrato_cobranca'];return$q;}
    private function resourceKind(PDO $pdo,array $account,string $externalId):string{$q=$pdo->prepare('SELECT provider_reference FROM installments i JOIN charges ch ON ch.id=i.charge_id WHERE ch.payment_account_id=? AND i.external_id=? LIMIT 1');$q->execute([$account['id'],$externalId]);$ref=(string)($q->fetchColumn()?:'');if(str_starts_with($ref,'sicoob:boleto:'))return'boleto';if(str_starts_with($ref,'sicoob:cobv:'))return'cobv';return'cob';}
    private function accessToken(PDO $pdo,array $a,string $product,array $mtls):string{$credentials=(array)($a['credentials']??[]);if(($a['environment']??'sandbox')==='sandbox'){$token=trim((string)($credentials['sandbox_access_token']??''));if($token==='')throw new RuntimeException('Access Token do sandbox não configurado.');return$token;}$prefix=$product==='pix'?'pix':'billing';$copy=$a;$copy['credentials']['client_id']=$credentials[$prefix.'_client_id']??$credentials['client_id']??'';$copy['credentials']['client_secret']=$credentials[$prefix.'_client_secret']??$credentials['client_secret']??'';$raw=(string)($a['provider_config'][$prefix.'_scopes']??'');$scopes=preg_split('/[\s,]+/',trim($raw),-1,PREG_SPLIT_NO_EMPTY)?:[];if($scopes===[])throw new RuntimeException('Scopes de '.$product.' não configurados conforme o aplicativo do Portal Sicoob.');return(new CobxOAuthTokenManager())->get($pdo,$copy,['token_url'=>self::TOKEN_URL,'grant_type'=>'client_credentials','client_auth'=>'body','scopes'=>$scopes],$mtls);}
    private function request(PDO $pdo,array $a,string $product,string $method,string $path,array $mtls,?array $json=null,?string $idempotency=null):CobxBankHttpResponse{$token=$this->accessToken($pdo,$a,$product,$mtls);$base=($a['environment']??'sandbox')==='production'?($product==='pix'?self::PIX_PROD:self::BILLING_PROD):($product==='pix'?self::PIX_SANDBOX:self::BILLING_SANDBOX);$credentials=(array)($a['credentials']??[]);$prefix=$product==='pix'?'pix':'billing';$clientId=(string)($credentials[$prefix.'_client_id']??$credentials['client_id']??'');$options=['bearer'=>$token,'mtls'=>$mtls,'headers'=>['client_id'=>$clientId],'retry_attempts'=>2];if($json!==null)$options['json']=$json;if($idempotency!==null)$options['idempotency_key']=$idempotency;return(new CobxBankHttpClient())->request($method,$base.$path,$options);}
    private function withMtls(PDO $pdo,array $a,callable $callback):mixed{$m=new CobxBankCertificateManager();$material=$m->material($pdo,(string)$a['id']);if(!$material||empty($material['certificate_pem'])||empty($material['private_key_pem']))throw new RuntimeException('certificado A1 e chave privada mTLS não configurados.');$files=$m->temporaryFiles($material);try{return$callback($files);}finally{$m->cleanup($files);}}
    private function failure(string $op,CobxBankHttpResponse $r):array{$j=$r->json();$message=is_array($j)?(string)($j['mensagem']??$j['detail']??$j['title']??''):'';return['ok'=>false,'detail'=>'Sicoob: falha ao '.$op.' (HTTP '.$r->status.')'.($message!==''?' - '.$message:'').'.'];}
}
