<?php
declare(strict_types=1);

require_once __DIR__.'/../api/common.php';require_once __DIR__.'/../api/db.php';
$mode=$argv[1]??'--dry-run';$backupArg='';foreach($argv as$arg)if(str_starts_with($arg,'--backup='))$backupArg=substr($arg,9);
$targets=[
 ['table'=>'companies','pk'=>'id','columns'=>['gateway_api_key','whatsapp_token','smtp_password']],
 ['table'=>'payment_accounts','pk'=>'id','columns'=>['api_key','webhook_secret','credentials_encrypted','token_cache_encrypted']],
 ['table'=>'payment_account_certificates','pk'=>'id','columns'=>['certificate_encrypted','private_key_encrypted','chain_encrypted','password_encrypted']],
 ['table'=>'master_settings','pk'=>'id','columns'=>['mercadopago_access_token','evolution_master_api_key','smtp_password','cron_secret','cronjob_api_key']],
];
$pdo=db();$legacy=[];foreach($targets as$t){$existing=[];foreach($pdo->query('SHOW COLUMNS FROM `'.$t['table'].'`')->fetchAll(PDO::FETCH_ASSOC)as$c)$existing[]=$c['Field'];$columns=array_values(array_intersect($t['columns'],$existing));if($columns===[])continue;$sql='SELECT `'.$t['pk'].'`,'.implode(',',array_map(static fn($c)=>'`'.$c.'`',$columns)).' FROM `'.$t['table'].'`';foreach($pdo->query($sql)->fetchAll(PDO::FETCH_ASSOC)as$row)foreach($columns as$column){$value=$row[$column]??null;if(is_string($value)&&$value!==''&&!str_starts_with($value,COBX_SECRET_PREFIX))$legacy[]=['table'=>$t['table'],'pk'=>$t['pk'],'id'=>(string)$row[$t['pk']],'column'=>$column,'value'=>$value];}}
if($mode==='--dry-run'){echo json_encode(['mode'=>'dry-run','legacy_count'=>count($legacy),'records'=>array_map(static fn($r)=>array_diff_key($r,['value'=>true]),$legacy)],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE),PHP_EOL;exit(0);}
if($mode==='--apply'){if($backupArg===''||file_exists($backupArg))throw new RuntimeException('Use --backup=CAMINHO_NOVO; o backup é obrigatório e não pode sobrescrever arquivo existente.');$backup=['created_at'=>date(DATE_ATOM),'database'=>(string)env('DB_DATABASE'),'records'=>$legacy];if(file_put_contents($backupArg,json_encode($backup,JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),LOCK_EX)===false)throw new RuntimeException('Falha ao gravar backup.');@chmod($backupArg,0600);$pdo->beginTransaction();try{foreach($legacy as$r)$pdo->prepare('UPDATE `'.$r['table'].'` SET `'.$r['column'].'`=? WHERE `'.$r['pk'].'`=?')->execute([cobx_secret_encrypt($r['value']),$r['id']]);$pdo->commit();}catch(Throwable$e){$pdo->rollBack();throw$e;}echo json_encode(['mode'=>'apply','migrated'=>count($legacy),'backup'=>$backupArg],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE),PHP_EOL;exit(0);}
if($mode==='--rollback'){if($backupArg===''||!is_file($backupArg))throw new RuntimeException('Informe --backup=CAMINHO_EXISTENTE.');$backup=json_decode((string)file_get_contents($backupArg),true,512,JSON_THROW_ON_ERROR);if(($backup['database']??'')!==(string)env('DB_DATABASE'))throw new RuntimeException('Backup pertence a outro banco.');$pdo->beginTransaction();try{foreach((array)($backup['records']??[])as$r)$pdo->prepare('UPDATE `'.$r['table'].'` SET `'.$r['column'].'`=? WHERE `'.$r['pk'].'`=?')->execute([$r['value'],$r['id']]);$pdo->commit();}catch(Throwable$e){$pdo->rollBack();throw$e;}echo json_encode(['mode'=>'rollback','restored'=>count($backup['records']??[])],JSON_PRETTY_PRINT),PHP_EOL;exit(0);}
throw new InvalidArgumentException('Uso: php scripts/legacy-secrets.php --dry-run | --apply --backup=arquivo | --rollback --backup=arquivo');
