<?php
declare(strict_types=1);
require_once __DIR__.'/../../api/common.php';require_once __DIR__.'/../../api/db.php';require_once __DIR__.'/../../api/lib/bank_account_store.php';require_once __DIR__.'/../../api/lib/payment_connector.php';require_once __DIR__.'/../../api/lib/gateway_payments.php';require_once __DIR__.'/../../api/routes/webhooks.php';
$pdo=db();$fail=[];$check=static function(bool $ok,string $message)use(&$fail):void{if(!$ok)$fail[]=$message;};$users=[uuid_v4(),uuid_v4()];
try{$companies=[uuid_v4(),uuid_v4()];foreach([0,1]as$n){$pdo->prepare('INSERT INTO users(id,email,password_hash)VALUES(?,?,?)')->execute([$users[$n],'audit-'.$users[$n].'@test.invalid','x']);$pdo->prepare('INSERT INTO companies(id,owner_id,name,is_active)VALUES(?,?,?,1)')->execute([$companies[$n],$users[$n],'Tenant '.$n]);}
$providers=['asaas','inter','sicoob','sicredi','santander','itau','bradesco'];$accounts=[];foreach($providers as$p){$id=uuid_v4();$accounts[$p]=$id;$pdo->prepare('INSERT INTO payment_accounts(id,company_id,name,provider,credentials_encrypted,provider_config,environment,is_default,is_active)VALUES(?,?,?,?,?,?,"sandbox",0,1)')->execute([$id,$companies[0],$p,$p,cobx_bank_credentials_encrypt(['api_key'=>'api','webhook_secret'=>'hook','webhook_token'=>'hook']),json_encode([])]);}
$payloads=['asaas'=>'{"event":"PAYMENT_RECEIVED","payment":{"id":"p1"}}','inter'=>'{"txid":"t1","status":"CONCLUIDA"}','sicoob'=>'{"pix":[]}','sicredi'=>'{"pix":[]}','santander'=>'{"txid":"t1"}','itau'=>'{"txid":"t1"}','bradesco'=>'{"pix":[]}'];foreach($payloads as$p=>$raw){$c=cobx_connector($p);$valid=$p==='asaas'?$c->verifyWebhook($pdo,$companies[0],$raw,['HTTP_ASAAS_ACCESS_TOKEN'=>'hook'],[]):$c->verifyWebhook($pdo,$companies[0],$raw,['SSL_CLIENT_VERIFY'=>'SUCCESS'],[]);$check($valid,$p.' recusou webhook válido.');$check(!$c->verifyWebhook($pdo,$companies[0],$raw,[],[]),$p.' aceitou webhook sem autenticação.');$check(!$c->verifyWebhook($pdo,$companies[1],$raw,['SSL_CLIENT_VERIFY'=>'SUCCESS','HTTP_ASAAS_ACCESS_TOKEN'=>'hook'],[]),$p.' aceitou tenant sem conta.');}
$client=uuid_v4();$charge=uuid_v4();$installment=uuid_v4();$pdo->prepare('INSERT INTO clients(id,company_id,name)VALUES(?,?,?)')->execute([$client,$companies[0],'Pagador']);$pdo->prepare("INSERT INTO charges(id,company_id,client_id,description,total_amount,installments_count,payment_gateway,payment_method,status)VALUES(?,?,?,'Teste',10,1,'asaas','pix','pending')")->execute([$charge,$companies[0],$client]);$pdo->prepare("INSERT INTO installments(id,charge_id,company_id,installment_number,amount,due_date,status,external_id)VALUES(?,?,?,1,10,CURDATE(),'pending','same-external')")->execute([$installment,$charge,$companies[0]]);
$first=cobx_payment_webhook_mark_paid($pdo,$companies[0],'asaas','same-external','',10,date(DATE_ATOM));$second=cobx_payment_webhook_mark_paid($pdo,$companies[0],'asaas','same-external','',10,date(DATE_ATOM));$foreign=cobx_payment_webhook_mark_paid($pdo,$companies[1],'asaas','same-external','',10,date(DATE_ATOM));$check(!empty($first['paid']),'Pagamento válido não foi baixado.');$check(empty($second['paid']),'Evento repetido baixou duas vezes.');$check(empty($foreign['paid']),'Webhook alterou outro tenant.');$check(cobx_gateway_account($pdo,$companies[1],$accounts['asaas'])===null,'Empresa B leu conta da A.');$check(cobx_connector_account_tokens($pdo,$companies[1],'asaas')===[],'Empresa B leu token da A.');
$check(cobx_payment_find_targets($pdo,$companies[0],'asaas','inexistente','',10)===[],'Referência inexistente encontrou parcela.');$nonFinancial=cobx_connector('asaas')->webhookEvents($pdo,$companies[0],'{"event":"PAYMENT_CREATED","payment":{"id":"x","status":"PENDING"}}',[]);$check(($nonFinancial[0]['status']??'')!=='paid','Evento não financeiro foi tratado como pagamento.');$check(!cobx_connector('asaas')->verifyWebhook($pdo,$companies[0],'{invalid',['HTTP_ASAAS_ACCESS_TOKEN'=>'errado'],[]),'Payload/token inválido aceito.');
$pdo->prepare("INSERT INTO payment_account_certificates(id,payment_account_id,format,certificate_encrypted)VALUES(?,?,'pem',?)")->execute([uuid_v4(),$accounts['asaas'],cobx_secret_encrypt('certificado-fixture')]);$cert=$pdo->prepare('SELECT 1 FROM payment_account_certificates pc JOIN payment_accounts pa ON pa.id=pc.payment_account_id WHERE pc.payment_account_id=? AND pa.company_id=?');$cert->execute([$accounts['asaas'],$companies[1]]);$check(!$cert->fetchColumn(),'Empresa B alcançou certificado da A.');$jobScope=$pdo->prepare('SELECT 1 FROM installments WHERE id=? AND company_id=?');$jobScope->execute([$installment,$companies[1]]);$check(!$jobScope->fetchColumn(),'Job da empresa B alcançou parcela da A.');
}finally{$pdo->prepare('DELETE FROM users WHERE id IN (?,?)')->execute($users);}echo json_encode(['ok'=>$fail===[],'failures'=>$fail],JSON_PRETTY_PRINT|JSON_UNESCAPED_UNICODE),PHP_EOL;exit($fail===[]?0:1);
